version: "3"

volumes:
  mongodb-data: {}

services:

  app:
    build: ./vue
    ports:
      - 9050:9050
    volumes:
      - ./vue:/usr/src/app
    stdin_open: true
    tty: true
    command: /bin/sh

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - "mongodb-data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
